### ISSUE TITLE
libcudart.so.5.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by WilliamRuRu15** [MVIG-SJTU/RMPE#7]
When I run `make runtest -j 8`, the error comes out like this. But I cannot find `libcudart.so.5.5` in cuda's lib (`/usr/local/cuda/lib64`). My cuda version is 8.0. Is this problem caused by version incompatibility?

**Comment by Fang-Haoshu** [comment]
Yes, I think so.
If you have successfully installed the code(make -j8), just try to run it without make runtest. It usually works.

**Comment by WilliamRuRu15** [comment]
Thanks, I'll try it.
